/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Dashboard: () => import('#controllers/dashboard_controller'),
  Events: () => import('#controllers/events_controller'),
  Export: () => import('#controllers/export_controller'),
  Features: () => import('#controllers/features_controller'),
  Integration: () => import('#controllers/integration_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Prd: () => import('#controllers/prd_controller'),
  Projects: () => import('#controllers/projects_controller'),
  PublicSignOff: () => import('#controllers/public_sign_off_controller'),
  PublicView: () => import('#controllers/public_view_controller'),
  Session: () => import('#controllers/session_controller'),
  Settings: () => import('#controllers/settings_controller'),
  SignOff: () => import('#controllers/sign_off_controller'),
  TestCases: () => import('#controllers/test_cases_controller'),
  UatFlows: () => import('#controllers/uat_flows_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
  Versions: () => import('#controllers/versions_controller'),
  ViewOnlyLinks: () => import('#controllers/view_only_links_controller'),
  YamlImport: () => import('#controllers/yaml_import_controller'),
  Steps: () => import('#controllers/steps_controller'),
}
