/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'details', 'entityId', 'entityType', 'id', 'ipAddress', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare details: any | null
  @column()
  declare entityId: string | null
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class EventSchema extends BaseModel {
  static $columns = ['condition', 'createdAt', 'deletedAt', 'description', 'expectedOutcome', 'id', 'model', 'name', 'notes', 'sequence', 'testStatus', 'triggerType', 'uatFlowId', 'updatedAt'] as const
  $columns = EventSchema.$columns
  @column()
  declare condition: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare expectedOutcome: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare model: string
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare sequence: number
  @column()
  declare testStatus: string
  @column()
  declare triggerType: string
  @column()
  declare uatFlowId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FeatureSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'ecosystem', 'id', 'inScope', 'module', 'name', 'outOfScope', 'priority', 'projectId', 'sequence', 'status', 'updatedAt', 'version'] as const
  $columns = FeatureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare ecosystem: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inScope: string | null
  @column()
  declare module: string | null
  @column()
  declare name: string
  @column()
  declare outOfScope: string | null
  @column()
  declare priority: string
  @column()
  declare projectId: string
  @column()
  declare sequence: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class PrdCompetitorSchema extends BaseModel {
  static $columns = ['competitorName', 'createdAt', 'id', 'productNameOrLink', 'projectId', 'sequence', 'updatedAt'] as const
  $columns = PrdCompetitorSchema.$columns
  @column()
  declare competitorName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productNameOrLink: string | null
  @column()
  declare projectId: string
  @column()
  declare sequence: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PrdContactSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'phone', 'projectId', 'sequence', 'title', 'updatedAt'] as const
  $columns = PrdContactSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare projectId: string
  @column()
  declare sequence: number
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PrdMilestoneSchema extends BaseModel {
  static $columns = ['completionDate', 'createdAt', 'department', 'id', 'projectId', 'sequence', 'startDate', 'status', 'updatedAt'] as const
  $columns = PrdMilestoneSchema.$columns
  @column()
  declare completionDate: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare department: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare projectId: string
  @column()
  declare sequence: number
  @column()
  declare startDate: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PrdOpenQuestionSchema extends BaseModel {
  static $columns = ['answer', 'createdAt', 'dateAnswered', 'id', 'projectId', 'question', 'sequence', 'updatedAt'] as const
  $columns = PrdOpenQuestionSchema.$columns
  @column()
  declare answer: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dateAnswered: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare projectId: string
  @column()
  declare question: string
  @column()
  declare sequence: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['additionalResources', 'additionalVisualIdentity', 'bom', 'brandingAdjectives', 'brandingTone', 'cloudApplication', 'companyName', 'contributors', 'createdAt', 'deletedAt', 'description', 'diagramsSchematics', 'firmwareFunctions', 'formFactor', 'generalComments', 'id', 'integrationConfig', 'integrationEnabled', 'locationsOfSale', 'materials', 'moduleList', 'name', 'objective', 'ownerId', 'packagingPresentation', 'prdDate', 'prdRequiredSignatures', 'prdSignatorIds', 'prdVersion', 'preparedBy', 'productName', 'projectManager', 'servicingUpdates', 'smartphoneApplication', 'status', 'successMetrics', 'targetAudience', 'targetMarket', 'targetReleaseDate', 'testerNames', 'testingEndDate', 'testingEndTime', 'testingStartDate', 'testingStartTime', 'touchpoint', 'uatAcceptanceRequiredSignatures', 'uatAcceptanceSignatorIds', 'uatImplementationRequiredSignatures', 'uatImplementationSignatorIds', 'updatedAt', 'userFeedback', 'userInteractions', 'visualIdentity'] as const
  $columns = ProjectSchema.$columns
  @column()
  declare additionalResources: string | null
  @column()
  declare additionalVisualIdentity: string | null
  @column()
  declare bom: string | null
  @column()
  declare brandingAdjectives: any | null
  @column()
  declare brandingTone: any | null
  @column()
  declare cloudApplication: string | null
  @column()
  declare companyName: string | null
  @column()
  declare contributors: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare diagramsSchematics: string | null
  @column()
  declare firmwareFunctions: string | null
  @column()
  declare formFactor: string | null
  @column()
  declare generalComments: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare integrationConfig: any | null
  @column()
  declare integrationEnabled: boolean
  @column()
  declare locationsOfSale: string | null
  @column()
  declare materials: string | null
  @column()
  declare moduleList: any | null
  @column()
  declare name: string
  @column()
  declare objective: string | null
  @column()
  declare ownerId: number | null
  @column()
  declare packagingPresentation: string | null
  @column()
  declare prdDate: string | null
  @column()
  declare prdRequiredSignatures: number
  @column()
  declare prdSignatorIds: any
  @column()
  declare prdVersion: string | null
  @column()
  declare preparedBy: string | null
  @column()
  declare productName: string | null
  @column()
  declare projectManager: string | null
  @column()
  declare servicingUpdates: string | null
  @column()
  declare smartphoneApplication: string | null
  @column()
  declare status: string
  @column()
  declare successMetrics: string | null
  @column()
  declare targetAudience: string | null
  @column()
  declare targetMarket: string | null
  @column()
  declare targetReleaseDate: string | null
  @column()
  declare testerNames: any | null
  @column()
  declare testingEndDate: string | null
  @column()
  declare testingEndTime: string | null
  @column()
  declare testingStartDate: string | null
  @column()
  declare testingStartTime: string | null
  @column()
  declare touchpoint: string | null
  @column()
  declare uatAcceptanceRequiredSignatures: number
  @column()
  declare uatAcceptanceSignatorIds: any
  @column()
  declare uatImplementationRequiredSignatures: number
  @column()
  declare uatImplementationSignatorIds: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userFeedback: string | null
  @column()
  declare userInteractions: string | null
  @column()
  declare visualIdentity: string | null
}

export class SignOffLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'signOffRecordId', 'signedAt', 'signerActualName', 'signerComments', 'signerEmail', 'signerIp', 'signerName', 'signerUserAgent', 'status', 'token', 'updatedAt'] as const
  $columns = SignOffLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare signOffRecordId: string
  @column.dateTime()
  declare signedAt: DateTime | null
  @column()
  declare signerActualName: string | null
  @column()
  declare signerComments: string | null
  @column()
  declare signerEmail: string
  @column()
  declare signerIp: string | null
  @column()
  declare signerName: string
  @column()
  declare signerUserAgent: string | null
  @column()
  declare status: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SignOffRecordSchema extends BaseModel {
  static $columns = ['createdAt', 'documentType', 'id', 'requestedAt', 'requestedById', 'requiredSignatures', 'signOffStage', 'status', 'updatedAt', 'versionId'] as const
  $columns = SignOffRecordSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentType: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare requestedAt: DateTime
  @column()
  declare requestedById: number | null
  @column()
  declare requiredSignatures: number
  @column()
  declare signOffStage: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare versionId: string
}

export class SignatorSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'projectId', 'sequence', 'title', 'updatedAt'] as const
  $columns = SignatorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare projectId: string
  @column()
  declare sequence: number
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StepImageSchema extends BaseModel {
  static $columns = ['createdAt', 'fileName', 'id', 'sequence', 'source', 'stepId', 'updatedAt'] as const
  $columns = StepImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare sequence: number
  @column()
  declare source: string
  @column()
  declare stepId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StepSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'gifFileName', 'id', 'name', 'sequence', 'uatFlowId', 'updatedAt'] as const
  $columns = StepSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare gifFileName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare sequence: number
  @column()
  declare uatFlowId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TestCaseSchema extends BaseModel {
  static $columns = ['createdAt', 'defectComments', 'deletedAt', 'descriptionOfTasks', 'expectedResults', 'fail', 'id', 'pass', 'sequence', 'stepsToExecute', 'testNo', 'uatFlowId', 'updatedAt'] as const
  $columns = TestCaseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defectComments: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descriptionOfTasks: string
  @column()
  declare expectedResults: string
  @column()
  declare fail: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare pass: boolean
  @column()
  declare sequence: number
  @column()
  declare stepsToExecute: string
  @column()
  declare testNo: number
  @column()
  declare uatFlowId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TriggerLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'eventId', 'id', 'isBroken', 'lastSyncAt', 'testStatus', 'triggerIdentifier', 'triggerModel', 'updatedAt'] as const
  $columns = TriggerLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isBroken: boolean
  @column.dateTime()
  declare lastSyncAt: DateTime | null
  @column()
  declare testStatus: string
  @column()
  declare triggerIdentifier: string
  @column()
  declare triggerModel: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UatFlowSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'featureId', 'id', 'name', 'preconditions', 'sequence', 'status', 'updatedAt', 'version'] as const
  $columns = UatFlowSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare featureId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare preconditions: string | null
  @column()
  declare sequence: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class UatTestLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'createdById', 'expiresAt', 'id', 'isActive', 'projectId', 'token', 'updatedAt'] as const
  $columns = UatTestLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: number | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare projectId: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UatTestResultSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'featureId', 'id', 'result', 'stepId', 'uatFlowId', 'uatTestSubmissionId', 'updatedAt'] as const
  $columns = UatTestResultSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare featureId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare result: string
  @column()
  declare stepId: string
  @column()
  declare uatFlowId: string
  @column()
  declare uatTestSubmissionId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UatTestSubmissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'signatorId', 'signature', 'signerIp', 'signerUserAgent', 'status', 'submittedAt', 'testerName', 'uatTestLinkId', 'updatedAt'] as const
  $columns = UatTestSubmissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare signatorId: string | null
  @column()
  declare signature: string | null
  @column()
  declare signerIp: string | null
  @column()
  declare signerUserAgent: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column()
  declare testerName: string
  @column()
  declare uatTestLinkId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UploadSchema extends BaseModel {
  static $columns = ['context', 'createdAt', 'fileName', 'filePath', 'id', 'mimeType', 'projectId', 'size', 'updatedAt'] as const
  $columns = UploadSchema.$columns
  @column()
  declare context: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string
  @column()
  declare projectId: string
  @column()
  declare size: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserGuideSectionSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'module', 'projectId', 'roleDescription', 'roleName', 'roleSequence', 'roleSlug', 'sequence', 'slug', 'status', 'title', 'updatedAt'] as const
  $columns = UserGuideSectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare module: string | null
  @column()
  declare projectId: string
  @column()
  declare roleDescription: string | null
  @column()
  declare roleName: string
  @column()
  declare roleSequence: number
  @column()
  declare roleSlug: string
  @column()
  declare sequence: number
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserGuideStepSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'imageFileName', 'instruction', 'sectionId', 'sequence', 'updatedAt'] as const
  $columns = UserGuideStepSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageFileName: string | null
  @column()
  declare instruction: string
  @column()
  declare sectionId: string
  @column()
  declare sequence: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VersionSchema extends BaseModel {
  static $columns = ['createdAt', 'createdById', 'documentType', 'id', 'projectId', 'snapshot', 'status', 'updatedAt', 'versionNumber'] as const
  $columns = VersionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: number | null
  @column()
  declare documentType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare projectId: string
  @column()
  declare snapshot: any | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare versionNumber: number
}

export class ViewOnlyLinkSchema extends BaseModel {
  static $columns = ['accessCount', 'createdAt', 'createdById', 'documentType', 'expiresAt', 'id', 'isActive', 'lastAccessedAt', 'passwordHash', 'projectId', 'token', 'updatedAt', 'version'] as const
  $columns = ViewOnlyLinkSchema.$columns
  @column()
  declare accessCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: number | null
  @column()
  declare documentType: string
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastAccessedAt: DateTime | null
  @column()
  declare passwordHash: string | null
  @column()
  declare projectId: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}
