/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type AuditLogTransformer from '#transformers/audit_log_transformer'
import type EventTransformer from '#transformers/event_transformer'
import type FeatureTransformer from '#transformers/feature_transformer'
import type ProjectTransformer from '#transformers/project_transformer'
import type SignOffLinkTransformer from '#transformers/sign_off_link_transformer'
import type SignOffRecordTransformer from '#transformers/sign_off_record_transformer'
import type TestCaseTransformer from '#transformers/test_case_transformer'
import type TriggerLinkTransformer from '#transformers/trigger_link_transformer'
import type UatFlowTransformer from '#transformers/uat_flow_transformer'
import type UploadTransformer from '#transformers/upload_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type VersionTransformer from '#transformers/version_transformer'
import type ViewOnlyLinkTransformer from '#transformers/view_only_link_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type AuditLog = InferData<AuditLogTransformer>
  export namespace AuditLog {
    export type Variants = InferVariants<AuditLogTransformer>
  }
  export type Event = InferData<EventTransformer>
  export namespace Event {
    export type Variants = InferVariants<EventTransformer>
  }
  export type Feature = InferData<FeatureTransformer>
  export namespace Feature {
    export type Variants = InferVariants<FeatureTransformer>
  }
  export type Project = InferData<ProjectTransformer>
  export namespace Project {
    export type Variants = InferVariants<ProjectTransformer>
  }
  export type SignOffLink = InferData<SignOffLinkTransformer>
  export namespace SignOffLink {
    export type Variants = InferVariants<SignOffLinkTransformer>
  }
  export type SignOffRecord = InferData<SignOffRecordTransformer>
  export namespace SignOffRecord {
    export type Variants = InferVariants<SignOffRecordTransformer>
  }
  export type TestCase = InferData<TestCaseTransformer>
  export namespace TestCase {
    export type Variants = InferVariants<TestCaseTransformer>
  }
  export type TriggerLink = InferData<TriggerLinkTransformer>
  export namespace TriggerLink {
    export type Variants = InferVariants<TriggerLinkTransformer>
  }
  export type UatFlow = InferData<UatFlowTransformer>
  export namespace UatFlow {
    export type Variants = InferVariants<UatFlowTransformer>
  }
  export type Upload = InferData<UploadTransformer>
  export namespace Upload {
    export type Variants = InferVariants<UploadTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Version = InferData<VersionTransformer>
  export namespace Version {
    export type Variants = InferVariants<VersionTransformer>
  }
  export type ViewOnlyLink = InferData<ViewOnlyLinkTransformer>
  export namespace ViewOnlyLink {
    export type Variants = InferVariants<ViewOnlyLinkTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
